import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/*
 * Each category links to its `<dir>/index` doc AND has autogenerated children.
 * Docusaurus does NOT dedupe the index doc out of the autogenerated children
 * in this nested form, so each `index.mdx` carries
 * `sidebar_class_name: category-index-hidden` and `src/css/custom.css` hides
 * the duplicate `<li>`.
 *
 * The cleaner Docusaurus-native alternative is `_category_.json` files in
 * each subdirectory + a fully-autogenerated sidebar (the convention then
 * dedupes natively). Worth considering if this file grows further.
 */

function cat(label: string, dir: string, items?: any[]) {
  return {
    type: "category" as const,
    label,
    link: { type: "doc" as const, id: `${dir}/index` },
    collapsible: true,
    collapsed: true,
    items: items ?? [{ type: "autogenerated" as const, dirName: dir }],
  };
}

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    "intro",
    cat("Power", "power", [
      cat("Generators", "power/generators"),
      cat("Energy Storage", "power/storage"),
      cat("Cables & Transformers", "power/cables"),
    ]),
    cat("Processing", "processing", [
      cat("LV Machines", "processing/lv-machines"),
      cat("MV Machines", "processing/mv-machines"),
      cat("HV+ Machines", "processing/hv-machines"),
    ]),
    cat("Tools & Armor", "tools-armor"),
    cat("Materials", "materials"),
    cat("Storage Units & Tanks", "storage"),
    cat("Multiblocks", "multiblocks"),
    cat("World", "world"),
    cat("Mechanics", "mechanics"),
    cat("Guides", "guides"),
  ],
};

export default sidebars;
