import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    "intro",
    {
      type: "category",
      label: "Power",
      collapsible: true,
      collapsed: true,
      items:[
        {
          type: "category",
          label: "Generators",
          items:[{ type: "autogenerated", dirName: "power/generators" }],
        },
        {
          type: "category",
          label: "Energy Storage",
          items:[{ type: "autogenerated", dirName: "power/storage" }],
        },
        {
          type: "category",
          label: "Cables & Transformers",
          items:[{ type: "autogenerated", dirName: "power/cables" }],
        },
      ],
    },
    {
      type: "category",
      label: "Processing",
      collapsible: true,
      collapsed: true,
      items:[
        {
          type: "category",
          label: "LV Machines",
          items:[{ type: "autogenerated", dirName: "processing/lv-machines" }],
        },
        {
          type: "category",
          label: "MV Machines",
          items:[{ type: "autogenerated", dirName: "processing/mv-machines" }],
        },
        {
          type: "category",
          label: "HV+ Machines",
          items:[{ type: "autogenerated", dirName: "processing/hv-machines" }],
        },
      ],
    },
    {
      type: "category",
      label: "Tools & Armor",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "tools-armor" }],
    },
    {
      type: "category",
      label: "Materials",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "materials" }],
    },
    {
      type: "category",
      label: "Storage Units & Tanks",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "storage" }],
    },
    {
      type: "category",
      label: "Multiblocks",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "multiblocks" }],
    },
    {
      type: "category",
      label: "World",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "world" }],
    },
    {
      type: "category",
      label: "Mechanics",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "mechanics" }],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: true,
      items:[{ type: "autogenerated", dirName: "guides" }],
    },
  ],
};

export default sidebars;
