const fs = require('fs');
const path = require('path');
const items = require('../src/data/items.json');

const manualMappings = {
  'techreborn:solid_fuel_generator': { displayName: 'Solid Fuel Generator', texture: '/img/blocks/generator_top.png', category: 'block' },
  'techreborn:water_mill': { displayName: 'Water Mill', texture: '/img/blocks/generator_top.png', category: 'block' },
  'techreborn:thermal_generator': { displayName: 'Thermal Generator', texture: '/img/blocks/thermal_generator_top_off.png', category: 'block' },
  'techreborn:diesel_generator': { displayName: 'Diesel Generator', texture: '/img/blocks/diesel_generator_top_off.png', category: 'block' },
  'techreborn:semi_fluid_generator': { displayName: 'Semi-Fluid Generator', texture: '/img/blocks/semi_fluid_generator_top_off.png', category: 'block' },
  'techreborn:plasma_generator': { displayName: 'Plasma Generator', texture: '/img/blocks/plasma_generator_top_off.png', category: 'block' },
  'techreborn:gas_turbine': { displayName: 'Gas Turbine', texture: '/img/blocks/generator_top.png', category: 'block' },
  'techreborn:lightning_rod': { displayName: 'Lightning Rod', texture: '/img/blocks/lightning_rod_top.png', category: 'block' },
  'techreborn:dragon_egg_syphon': { displayName: 'Dragon Egg Syphon', texture: '/img/blocks/dragon_egg_syphon_top.png', category: 'block' },
  'techreborn:basic_machine_frame': { displayName: 'Basic Machine Frame', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:advanced_machine_frame': { displayName: 'Advanced Machine Frame', texture: '/img/blocks/advanced_machine_casing.png', category: 'block' },
  'techreborn:industrial_machine_frame': { displayName: 'Industrial Machine Frame', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:electric_furnace': { displayName: 'Electric Furnace', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:grinder': { displayName: 'Grinder', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:compressor': { displayName: 'Compressor', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:extractor': { displayName: 'Extractor', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:alloy_smelter': { displayName: 'Alloy Smelter', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:chemical_reactor': { displayName: 'Chemical Reactor', texture: '/img/blocks/advanced_machine_casing.png', category: 'block' },
  'techreborn:assembly_machine': { displayName: 'Assembly Machine', texture: '/img/blocks/advanced_machine_casing.png', category: 'block' },
  'techreborn:distillation_tower': { displayName: 'Distillation Tower', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:implosion_compressor': { displayName: 'Implosion Compressor', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:industrial_blast_furnace': { displayName: 'Industrial Blast Furnace', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:industrial_centrifuge': { displayName: 'Industrial Centrifuge', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:industrial_electrolyzer': { displayName: 'Industrial Electrolyzer', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:industrial_grinder': { displayName: 'Industrial Grinder', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:industrial_sawmill': { displayName: 'Industrial Sawmill', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:vacuum_freezer': { displayName: 'Vacuum Freezer', texture: '/img/blocks/industrial_machine_casing.png', category: 'block' },
  'techreborn:wire_mill': { displayName: 'Wire Mill', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:recycler': { displayName: 'Recycler', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:rolling_machine': { displayName: 'Rolling Machine', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:auto_crafting_table': { displayName: 'Auto Crafting Table', texture: '/img/blocks/auto_crafting_table_top.png', category: 'block' },
  'techreborn:iron_alloy_furnace': { displayName: 'Iron Alloy Furnace', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:iron_furnace': { displayName: 'Iron Furnace', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:solid_canning_machine': { displayName: 'Solid Canning Machine', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:scrapboxinator': { displayName: 'Scrapboxinator', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:matter_fabricator': { displayName: 'Matter Fabricator', texture: '/img/blocks/matter_fabricator_bottom.png', category: 'block' },
  'techreborn:fishing_station': { displayName: 'Fishing Station', texture: '/img/blocks/fishing_station.png', category: 'block' },
  'techreborn:low_voltage_su': { displayName: 'LV Storage Unit', texture: '/img/blocks/low_voltage_su_front.png', category: 'block' },
  'techreborn:medium_voltage_su': { displayName: 'MV Storage Unit', texture: '/img/blocks/medium_voltage_su_front.png', category: 'block' },
  'techreborn:high_voltage_su': { displayName: 'HV Storage Unit', texture: '/img/blocks/high_voltage_su_front.png', category: 'block' },
  'techreborn:lapotronic_su': { displayName: 'Lapotronic SU', texture: '/img/blocks/lapotronic_su_front.png', category: 'block' },
  'techreborn:adjustable_su': { displayName: 'Adjustable SU', texture: '/img/blocks/adjustable_su_front.png', category: 'block' },
  'techreborn:interdimensional_su': { displayName: 'Interdimensional SU', texture: '/img/blocks/interdimensional_su_front.png', category: 'block' },
  'techreborn:lv_transformer': { displayName: 'LV Transformer', texture: '/img/blocks/lv_transformer_front.png', category: 'block' },
  'techreborn:mv_transformer': { displayName: 'MV Transformer', texture: '/img/blocks/mv_transformer_front.png', category: 'block' },
  'techreborn:hv_transformer': { displayName: 'HV Transformer', texture: '/img/blocks/hv_transformer_front.png', category: 'block' },
  'techreborn:basic_solar_panel': { displayName: 'Basic Solar Panel', texture: '/img/blocks/basic_solar_panel_top.png', category: 'block' },
  'techreborn:advanced_solar_panel': { displayName: 'Advanced Solar Panel', texture: '/img/blocks/advanced_solar_panel_top.png', category: 'block' },
  'techreborn:industrial_solar_panel': { displayName: 'Industrial Solar Panel', texture: '/img/blocks/industrial_solar_panel_top.png', category: 'block' },
  'techreborn:ultimate_solar_panel': { displayName: 'Ultimate Solar Panel', texture: '/img/blocks/ultimate_solar_panel_top.png', category: 'block' },
  'techreborn:quantum_solar_panel': { displayName: 'Quantum Solar Panel', texture: '/img/blocks/quantum_solar_panel_top.png', category: 'block' },
  'techreborn:creative_solar_panel': { displayName: 'Creative Solar Panel', texture: '/img/blocks/creative_solar_panel_top.png', category: 'block' },
  'techreborn:basic_tank_unit': { displayName: 'Basic Tank Unit', texture: '/img/blocks/basic_tank_unit_top.png', category: 'block' },
  'techreborn:advanced_tank_unit': { displayName: 'Advanced Tank Unit', texture: '/img/blocks/advanced_tank_unit_top.png', category: 'block' },
  'techreborn:industrial_tank_unit': { displayName: 'Industrial Tank Unit', texture: '/img/blocks/industrial_tank_unit_top.png', category: 'block' },
  'techreborn:quantum_tank_unit': { displayName: 'Quantum Tank Unit', texture: '/img/blocks/creative_tank_unit_top.png', category: 'block' },
  'techreborn:fusion_control_computer': { displayName: 'Fusion Control Computer', texture: '/img/blocks/fusion_control_computer_bottom.png', category: 'block' },
  'techreborn:fusion_coil': { displayName: 'Fusion Coil', texture: '/img/blocks/fusion_coil_heart.png', category: 'block' },
  'techreborn:chunk_loader': { displayName: 'Chunk Loader', texture: '/img/blocks/chunk_loader_top.png', category: 'block' },
  'techreborn:lsu_storage': { displayName: 'LSU Storage', texture: '/img/blocks/basic_storage_unit_top.png', category: 'block' },
  'techreborn:storage_buffer': { displayName: 'Storage Buffer', texture: '/img/blocks/basic_storage_unit_top.png', category: 'block' },
  'techreborn:player_detector': { displayName: 'Player Detector', texture: '/img/blocks/player_detector_all.png', category: 'block' },
  'techreborn:block_breaker': { displayName: 'Block Breaker', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:block_placer': { displayName: 'Block Placer', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:drain': { displayName: 'Drain', texture: '/img/blocks/fluid_drain_top.png', category: 'block' },
  'techreborn:pump': { displayName: 'Pump', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:launchpad': { displayName: 'Launchpad', texture: '/img/blocks/launchpad_top.png', category: 'block' },
  'techreborn:alarm': { displayName: 'Alarm', texture: '/img/blocks/lamp.png', category: 'block' },
  'techreborn:lamp_incandescent': { displayName: 'Incandescent Lamp', texture: '/img/blocks/lamp.png', category: 'block' },
  'techreborn:lamp_led': { displayName: 'LED Lamp', texture: '/img/blocks/lamp.png', category: 'block' },
  'techreborn:charge_o_mat': { displayName: 'Charge-O-Mat', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:elevator': { displayName: 'Elevator', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:fluid_replicator': { displayName: 'Fluid Replicator', texture: '/img/blocks/advanced_machine_casing.png', category: 'block' },
  'techreborn:greenhouse_controller': { displayName: 'Greenhouse Controller', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:resin_basin': { displayName: 'Resin Basin', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'techreborn:rock_cutter': { displayName: 'Rock Cutter', texture: '/img/items/rock_cutter.png', category: 'item' },
  'techreborn:painting_tool': { displayName: 'Painting Tool', texture: '/img/items/painting_tool.png', category: 'item' },
  'techreborn:scrap_box': { displayName: 'Scrap Box', texture: '/img/items/scrapbox.png', category: 'item' },
  'techreborn:computer_cube': { displayName: 'Computer Cube', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
  'minecraft:furnace': { displayName: 'Furnace', texture: '/img/blocks/basic_machine_casing.png', category: 'block' },
};

let added = 0;
for (const [id, data] of Object.entries(manualMappings)) {
  if (!items[id]) {
    items[id] = data;
    added++;
  }
}

console.log('Added', added, 'manual entries. Total:', Object.keys(items).length);
fs.writeFileSync(path.join(__dirname, '../src/data/items.json'), JSON.stringify(items, null, 2));
